import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Cinzel_Decorative } from "@next/font/google";

const cinzelDecorative = Cinzel_Decorative({
  weight: ["400", "700"], // Choose the font weights you need
  subsets: ["latin"], // Include subsets (default is 'latin')
});
export const metadata: Metadata = {
  title: "Sreyashir Gaynar Baksho",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-custom-bg-light ${cinzelDecorative.className} p-0 m-0 h-screen w-screen`}
      >
        <Navbar />
        <div className="w-screen">{children}</div>
      </body>
    </html>
  );
}
